<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFwjdbdn\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFwjdbdn/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFwjdbdn.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFwjdbdn\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFwjdbdn\srcDevDebugProjectContainer([
    'container.build_hash' => 'Fwjdbdn',
    'container.build_id' => '59f85092',
    'container.build_time' => 1579015595,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFwjdbdn');
